main:
    random_seed: 0
    saved_dir: '/home/vincentwu-cmlab/nips2019/models/kits_seg/vnet/'

dataset:
    name: 'KitsSegDataset'
    kwargs:
        data_dir: "/media/vincentwu-cmlab/5aae4c8c-ef9b-414c-acc3-814927dbe8b7/kits19/data/"
        data_split_csv: "/media/vincentwu-cmlab/5aae4c8c-ef9b-414c-acc3-814927dbe8b7/kits19/dataset_split.csv"
        positive_sampling_rate: 1.0
        sample_size: [192, 192, 16]
        preprocessings:
            - name: 'Normalize'
        transforms:
            - name: 'ToTensor'
        augments:
            - name: 'RandomHorizontalFlip'
              kwargs:
                  prob: 0.25
            - name: 'RandomVerticalFlip'
              kwargs:
                  prob: 0.25

dataloader:
    name: 'Dataloader'
    kwargs:
        train_batch_size: 2
        valid_batch_size: 1
        shuffle: true
        num_workers: 8

net:
    name: 'VNet'
    kwargs:
        in_channels: 1
        out_channels: 3

losses:
    - name: 'DiceLoss'
      weight: 1.0

metrics:
    - name: 'Dice'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.001
        weight_decay: 0
        amsgrad: false

logger:
    name: 'KitsSegLogger'
    kwargs:
        dummy_input: [16, 1, 256, 256]

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'max'
        target: 'Dice'
        saved_freq: 10
        early_stop: 0

trainer:
    name: 'KitsSegTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 100